apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fluxcd.io/sync-gc-mark: sha256.rEjArE-Ap1Hr9U06zGi4uYVOP8h_T_Os57GgkuVq3Og
  name: podinfo
spec:
  ports:
  - port: 9898
    protocol: TCP
    targetPort: 9898
    nodePort: 30001
  selector:
    app: podinfo
  type: NodePort
status:
  loadBalancer: {}
