apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webapp
    spec:
      containers:
      - image: nginx
        name: webapp
        resources: {}
status: {}
