apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-webapp
  name: my-webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31111
  selector:
    run: my-webapp
  type: NodePort
status:
  loadBalancer: {}
